- hosts: all
  sudo: true
  user: ec2-user
  vars:
    locale: ja_JP.UTF-8
    zone: Asia/Tokyo
    zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo
    log_dir: '/tmp/cloudtrail'
  vars_prompt:
    - name: aws_access_key_id
      prompt: "Please enter your aws_access_key_id"
      private: no
    - name: aws_secret_access_key
      prompt: "Please enter your aws_secret_access_key(secret)"
      private: yes
    - name: cloudtrail_s3_path
      prompt: "Please enabled CloudTrail s3 path ex.'xxcloudtrail/AWSLogs/7xxxxxxx5x3/CloudTrail/ap-northeast-1/2015/02'"
      private: no
  tasks:
    - name: set locale to /etc/cloud/cloud.cfg
      lineinfile: 'dest=/etc/cloud/cloud.cfg line="locale: {{locale}}"'
    - name: set locale to /etc/sysconfig/i18n
      replace: >
        dest=/etc/sysconfig/i18n
        regexp='^LANG=en_US\.UTF-8'
        replace='LANG={{locale}}'
    - name: set zone to /etc/sysconfig/clock
      replace: >
        dest=/etc/sysconfig/clock
        regexp='^ZONE=\"UTC\"'
        replace='ZONE="{{zone}}"'
    - name: set localtime
      file: >
        src={{zoneinfo_path}}
        dest=/etc/localtime
        state=link
        force=yes
    - name: yum update
      yum: state=latest name=*
    - name: copy mongodb.repo
      copy: src=repos/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root
    - name: install mongodb
      yum: pkg=mongodb-org enablerepo=mongodb
    - name: start mongodb
      service: name=mongod state=started
    - name: install jq
      yum: pkg=jq state=installed
    - name: make to save CloudTrail log directory
      file: dest={{log_dir}} state=directory mode="u=rxw,g=rxw,o=rxw"
    - name: get CloudTrail logs from s3
      command: sh -c 'AWS_ACCESS_KEY_ID={{aws_access_key_id}} AWS_SECRET_ACCESS_KEY={{aws_secret_access_key}} aws s3 sync s3://{{cloudtrail_s3_path}} {{log_dir}}'
    - name: insert CloudTrail log to MongoDB
      command: sh -c 'for x in `find {{log_dir}} -name "*.json.gz"` ; do zcat $x | jq .Records[] | mongoimport --collection cloudtrail --jsonArray ; done'
